#!/bin/bash
# Run an inside grep on enviro vars
#

#set -x

	usage(){
	   			echo " "
	   			echo " "
	   			echo " "
	   			echo "Usage:   $0 needle					-Search enviro vars for needle.  Default: CASE sensative!"
	   			echo " "
	   			echo " 														-Add 1 switch for grep if need be."
	   			echo " "
		exit 1
	}

	switch=
	needle=

	if [ $# -lt 0 ]
  		then
				usage
	fi


	if [  "$1" == "-H" ] || [ "$1" == "-h" ]
  		then
				usage
  fi
	

	if [ $# -gt 1 ]
  		then
				switch="$1"
				needle="$2"

				env |grep "$switch" "$needle"
	else
				needle="$1"

				env |grep "$needle"
	fi

	

	echo " "
	echo " "	
